import "@primer/css/index.scss";

import AuthProvider from "../lib/auth/AuthProvider";
import Header from "../components/Header";
import Navbar from "../components/Navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Header />
          <div className="d-flex flex-row">
            <Navbar />
            {children}
          </div>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
