import "@primer/css/index.scss";

import AuthProvider from "../lib/auth/AuthProvider";
import Header from "../components/Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Header />
          <div className="d-flex flex-row">
            <nav className="SideNav border">
              {" "}
              <a className="SideNav-item" href="#url">
                Account
              </a>
              <a className="SideNav-item" href="#url" aria-current="page">
                Profile
              </a>
              <a className="SideNav-item" href="#url">
                Emails
              </a>
              <a className="SideNav-item" href="#url">
                Notifications
              </a>
            </nav>
            {children}
          </div>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
